version: '3'

services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile  # Путь к Dockerfile для веб-приложения
    image: bus_flask
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: db/Dockerfile  # Путь к Dockerfile PostgreSQL
    environment:
      POSTGRES_DB: bus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
    ports:
      - "5432:5432"
    volumes:
      - ./path/to/data:/var/lib/postgresql/data  # Путь к каталогу, где будут храниться данные PostgreSQL
