version: '3'

services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    image: bus_flask
    ports:
      - "5000:5000"
    depends_on:
      - db
  generator:
    build:
      context: .
      dockerfile: generator/Dockerfile
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: bus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
    ports:
      - "5432:5432"
    volumes:
      - ./path/to/data:/var/lib/postgresql/data
